version: "3"
services:
  backend:
    build: ./backend
    volumes:
      - ./shared_folder:/app/shared_folder
    ports:
      - "8000:8000"


  frontend:
    build: ./frontend
    volumes:
      - ./shared_folder:/app/shared_folder
    ports:
      - "8501:8501"
    depends_on:
      - backend

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: unless-stopped
    ports:
      - "9100:9100"  # Expose Node Exporter metrics on port 910
    volumes:
      - /proc:/host/proc


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"  # Prometheus Web UI on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Grafana Web UI on port 3000
    volumes:
      - ./grafana_data:/var/lib/grafana  # <<<<<< Add this line